USE [master]
GO

/****** Object:  Database [MoviesHub]    Script Date: 6/9/2021 5:26:01 PM ******/
CREATE DATABASE [MoviesHub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoviesHub', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviesHub.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoviesHub_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviesHub_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoviesHub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoviesHub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoviesHub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoviesHub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoviesHub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoviesHub] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoviesHub] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MoviesHub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoviesHub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoviesHub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoviesHub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoviesHub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoviesHub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoviesHub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoviesHub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoviesHub] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MoviesHub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoviesHub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoviesHub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoviesHub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoviesHub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoviesHub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoviesHub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoviesHub] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MoviesHub] SET  MULTI_USER 
GO

ALTER DATABASE [MoviesHub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoviesHub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoviesHub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoviesHub] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoviesHub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoviesHub] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MoviesHub] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MoviesHub] SET  READ_WRITE 
GO

