# Generated by Django 2.1.15 on 2021-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
    ]
