# Generated by Django 2.1.15 on 2021-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombreUser', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=200)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
