# Generated by Django 2.1.15 on 2021-06-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptor',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='apellidos',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='suscriptor',
            old_name='nombreUser',
            new_name='username',
        ),
    ]
